'''
Triangular, pentagonal, and hexagonal
Problem 45 

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

'''
Hn = n(2n-1) = 2n(2n-1)/2
let a = 2n - 1

Hn = Ta
'''

n = 1
time = 0

def judge_pentagonal(num):
    i = 1
    while True:
        checkNum = i * (3 * i - 1) / 2
        if checkNum == num:
            return True
        if checkNum > num:
            return False
        i += 1

while True:
    num = n * (2 * n - 1)
    if judge_pentagonal(num):
        time += 1
        if time == 3:
            print num
            break
    n += 1